### ISSUE TITLE
Upload builds to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [DrSensor/F.I.D.E#1]
Please upload builds to GitHub Releases for easy downloading and integration into the [AppImageHub](https://appimage.github.io/apps/) central directory of available AppImages.

**Comment by DrSensor** [comment]
Done, it can be found [here](https://github.com/DrSensor/F.I.D.E/releases)

**Comment by probonopd** [comment]
Unfortunately I don't see an AppImage at https://github.com/DrSensor/F.I.D.E/releases, can you please check? Thanks.

**Comment by DrSensor** [comment]
Sorry, forgot that is still in Draft status.
I just updated it. Is it visible now @probonopd?
